In [1]:
import pandas as pd

In [9]:
df=pd.read_csv("home_price3.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [10]:
df.bedrooms.median()


3.5

In [13]:
import math
median_bedroom=math.floor(df.bedrooms.median())
median_bedroom

3

In [14]:
df.bedrooms=df.bedrooms.fillna(median_bedroom)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [15]:
from sklearn import linear_model

In [16]:
reg=linear_model.LinearRegression()
reg.fit(df[['bedrooms','age','area']],df.price)


LinearRegression()

In [17]:
reg.coef_

array([-26025.  ,  -6825.  ,    137.25])

In [19]:
reg.intercept_

383725.0000000005

In [20]:
reg.predict([[3,40,3000]])

/home/nituhimani/.local/lib/python3.9/site-packages/sklearn/base.py:409: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([444400.])

In [4]:
import numpy as np

def gradient_descent(x,y):
    m_curr = b_curr = 0
    iterations = 10
    n = len(x)
    learning_rate = 0.08

    for i in range(iterations):
        y_predicted = m_curr * x + b_curr
        cost = (1/n) * sum([val**2 for val in (y-y_predicted)])
        md = -(2/n)*sum(x*(y-y_predicted))
        bd = -(2/n)*sum(y-y_predicted)
        m_curr = m_curr - learning_rate * md
        b_curr = b_curr - learning_rate * bd
        print ("m {}, b {}, cost {} iteration {}".format(m_curr,b_curr,cost, i))

x = np.array([1,2,3,4,5])
y = np.array([5,7,9,11,13])

gradient_descent(x,y)

m 4.96, b 1.44, cost 89.0 iteration 0
m 0.4991999999999983, b 0.26879999999999993, cost 71.10560000000002 iteration 1
m 4.451584000000002, b 1.426176000000001, cost 56.8297702400001 iteration 2
m 0.892231679999997, b 0.5012275199999995, cost 45.43965675929613 iteration 3
m 4.041314713600002, b 1.432759910400001, cost 36.35088701894832 iteration 4
m 1.2008760606719973, b 0.7036872622079998, cost 29.097483330142282 iteration 5
m 3.7095643080294423, b 1.4546767911321612, cost 23.307872849944438 iteration 6
m 1.4424862661541864, b 0.881337636696883, cost 18.685758762535738 iteration 7
m 3.4406683721083144, b 1.4879302070713722, cost 14.994867596913156 iteration 8
m 1.6308855378034224, b 1.0383405553279617, cost 12.046787238456794 iteration 9


In [11]:
import pickle


In [14]:
import pandas as pd

In [15]:
df=pd.read_csv("home_price2.csv")
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [17]:
from sklearn import linear_model

In [18]:
model=linear_model.LinearRegression()
model.fit(df[['area']],df.price)


with open('model_pickle','wb')as f:
    pickle.dump(model,f)


In [19]:
model.coef_

array([135.78767123])

In [20]:
model.intercept_

180616.43835616432

In [21]:
model.predict([[5000]])

/home/nituhimani/.local/lib/python3.9/site-packages/sklearn/base.py:409: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [22]:
import pickle

In [26]:
with open('model_pickle','wb') as f:
    pickle.dump(model,f)

In [27]:
with open('model_pickle','rb')as f:
    mp=pickle.load(f)

In [28]:
mp.predict([[5000]])

/home/nituhimani/.local/lib/python3.9/site-packages/sklearn/base.py:409: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [31]:
import joblib

In [32]:

joblib.dump(model,'model_joblib')



['model_joblib']

In [34]:
mj=joblib.load('model_joblib')


In [35]:
mj.predict([[5000]])

/home/nituhimani/.local/lib/python3.9/site-packages/sklearn/base.py:409: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])