In [6]:
import pandas as pd
import numpy as np

In [12]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits
digits=load_digits()

In [16]:
from sklearn.model_selection import cross_val_score



In [17]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'),digits.data,digits.target,cv=3)

array([0.89482471, 0.95325543, 0.90984975])

In [18]:
cross_val_score(SVC(gamma='auto'),digits.data,digits.target,cv=3)

array([0.38063439, 0.41068447, 0.51252087])

In [19]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target,cv=3)

array([0.94323873, 0.95158598, 0.92654424])

Hence it is clear that random forest classifier gives us the most aqurate answer compair than other two.. 